# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 337)
        MainWindow.setMaximumSize(QtCore.QSize(350, 350))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background:transparent;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 300, 300))
        
        self.frame_2.setStyleSheet("QFrame{\n"
"    border-radius:  150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90,\n"
"    stop:0.749 rgba(255, 0, 127,0), \n"
"    stop:0.750 rgba(68, 10, 103));\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.frame_3.setStyleSheet("border-radius: 149px;\n"
"border:None;\n"
"background-color: rgb(147, 50, 158);\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(25, 25, 270, 270))
        self.frame_4.setStyleSheet("QFrame{\n"
"    border-radius: 135px;\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(180, 174, 232);\n"
"\n"
"    \n"
"    \n"
"    \n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(80, 31, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;\n"
"color: rgb(166, 246, 241);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 192, 21))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:none;\n"
"\n"
"\n"
"color: rgb(47, 47, 71);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(120, 90, 41, 41))
        self.pushButton.setStyleSheet("QPushButton{    \n"
"    border:None;\n"
"    background-color: rgb(41, 63, 203,0);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"\n"
"    \n"
"    background-color: rgb(227, 107, 174);\n"
"    \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 131, 20))
        self.label_2.setStyleSheet("color: rgb(68, 10, 103);")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setGeometry(QtCore.QRect(250, 130, 16, 16))
        self.lineEdit.setStyleSheet("QLineEdit{ \n"
"    border: 0px solid gray;\n"
"    background:transparent;\n"
"                                     \n"
"     \n"
"    color: rgb(180, 174, 232);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 140, 81, 21))
        self.pushButton_2.setStyleSheet("QPushButton{    \n"
"    border:None;\n"
"    \n"
"    \n"
"    color: rgb(147, 50, 158);\n"
"    border-radius: 10px;\n"
"    \n"
"    color: rgb(255, 0, 127);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(70, 190, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    \n"
"    border-radius:  10px;\n"
"    \n"
"    \n"
"    background-color: rgb(255, 0, 127);\n"
"    font: 9pt \"MV Boli\";\n"
"    background-color: rgb(180, 174, 232);\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    \n"
"}")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 230, 41, 41))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icon\\facbooke1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(292, 0, 21, 21))
        self.pushButton_3.setStyleSheet("QPushButton{    \n"
"    \n"
"    \n"
"    background-color: rgb(83, 95, 127);\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(255, 25, 75);\n"
"    \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 0, 21, 21))
        self.pushButton_4.setStyleSheet("QPushButton{    \n"
"    \n"
"    \n"
"    background-color: rgb(83, 95, 127);\n"
"\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(0, 255, 0);\n"
"    \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#515c7c;\">by:Abdulrahman-MiDo-D3vil</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "pdf"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">P</span><span style=\" font-weight:600;\">df_to_</span><span style=\" font-size:10pt; font-weight:600;\">D</span><span style=\" font-weight:600;\">ocx</span></p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", "lklkbnljnbkjbkjbjkhbvjhvfcytdfytdytdytdytdytdtydyt"))
        self.pushButton_2.setText(_translate("MainWindow", "Convert"))
        self.pushButton_3.setText(_translate("MainWindow", "X"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
